FROM registry.cn-beijing.aliyuncs.com/zexi/ubuntu:25.04

ENV LC_ALL=en_US.utf8

RUN apt update && apt install -y \
	libegl1-mesa-dev libgl1-mesa-dev libopus-dev libsdl2-dev libsdl2-ttf-dev libssl-dev libavcodec-dev libavformat-dev libswscale-dev libva-dev libvdpau-dev libxkbcommon-dev wayland-protocols libdrm-dev \
	qt6-base-dev qt6-declarative-dev libqt6svg6-dev qml6-module-qtquick-controls qml6-module-qtquick-templates qml6-module-qtquick-layouts qml6-module-qtqml-workerscript qml6-module-qtquick-window qml6-module-qtquick make g++

RUN <<_GSTREAMER_INSTALL
    #!/bin/bash
    set -e

    DEV_PACKAGES=" \
        build-essential ninja-build gcc meson cmake ccache bison equivs \
        ca-certificates git libllvm15 \
        flex libx265-dev libopus-dev nasm libzxing-dev libzbar-dev libdrm-dev libva-dev \
        libunwind8 libcap2-bin \
        libx11-dev libx11-xcb-dev libxfixes-dev libxdamage-dev libwayland-dev wayland-protocols libpulse-dev libglib2.0-dev \
        libopenjp2-7-dev liblcms2-dev libcairo2-dev libcairo-gobject2 libwebp7 librsvg2-dev libaom-dev \
        libharfbuzz-dev libpango1.0-dev libsoup-2.4-1 libopengl-dev libgbm-dev libegl-dev \
        libglu1-mesa-dev freeglut3-dev mesa-common-dev libgl1-mesa-dev libgles-dev libgl-dev libglx-dev libgudev-1.0-dev
        "
    apt-get install -y --no-install-recommends $DEV_PACKAGES
_GSTREAMER_INSTALL

